name: Check GSR testROM accuracy
on: [push, pull_request]
jobs:
  Check-TestROMs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install dependencies
        run: "sudo apt install scons"

      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          path: gambatte-speedrun
      
      - name: Assemble TestROMs
        run: "cd gambatte-speedrun/test && sh scripts/assemble_tests.sh"

      - name: Build libgambatte and run tests
        run: "cd gambatte-speedrun && sh scripts/test.sh"
